name: Build and Test

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 16
          cache: npm

      - name: Install NPM Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

  shadowbox:
    name: Shadowbox
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 16
          cache: npm

      - name: Install NPM Dependencies
        run: npm ci

      - name: Shadowbox Debug Build
        run: npm run action shadowbox/server/build

      - name: Shadowbox Unit Test
        run: npm run action shadowbox/test

      - name: Shadowbox Integration Test
        run: npm run action shadowbox/integration_test/run

  metrics-server:
    name: Metrics Server
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 16
          cache: npm

      - name: Install NPM Dependencies
        run: npm ci

      - name: Metrics Server Debug Build
        run: npm run action metrics_server/build

      - name: Metrics Server Test
        run: npm run action metrics_server/test

  manager-web-test:
    name: Manager Web Test
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 16
          cache: npm

      - name: Install NPM Dependencies
        run: npm ci

      - name: Manager Web Test
        run: npm run action server_manager/test

  manager-linux-debug-build:
    name: Manager Linux Debug Build
    runs-on: ubuntu-latest
    needs: manager-web-test
    env:
      SENTRY_DSN: debug
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 16
          cache: npm

      - name: Install NPM Dependencies
        run: npm ci

      - name: Build Linux Manager
        run: npm run action server_manager/electron_app/build --platform linux

      - name: Upload Linux Client
        uses: actions/upload-artifact@v2
        with:
          name: manager_linux_debug
          path: build/server_manager/electron_app/static/dist/Outline-Manager.AppImage
          if-no-files-found: error

  manager-windows-debug-build:
    name: Manager Windows Debug Build
    runs-on: windows-2019
    needs: manager-web-test
    env:
      SENTRY_DSN: debug
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 16
          cache: npm

      - name: Install NPM Dependencies
        run: npm ci

      - name: Build Windows Manager
        run: npm run action server_manager/electron_app/build --platform windows

      - name: Upload Windows Manager
        uses: actions/upload-artifact@v2
        with:
          name: manager_windows_debug
          path: build/server_manager/electron_app/static/dist/Outline-Manager.exe
          if-no-files-found: error

  manager-mac-debug-build:
    name: Manager MacOS Debug Build
    runs-on: macos-11
    needs: manager-web-test
    env:
      SENTRY_DSN: debug
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 16
          cache: npm

      - name: Install NPM Dependencies
        run: npm ci

      - name: Set XCode Version
        run: sudo xcode-select -switch /Applications/Xcode_13.2.app

      - name: Build MacOS Manager
        run: npm run action server_manager/electron_app/build --platform mac

      - name: Upload MacOS Manager
        uses: actions/upload-artifact@v2
        with:
          name: manager_macos_debug
          path: build/server_manager/electron_app/static/dist/Outline-Manager.dmg
          if-no-files-found: error
