name: Build Linux Release Candidate

on:
  workflow_call:
    secrets:
      SENTRY_DSN:
        required: true

jobs:
  manager-linux-release-build:
    name: Manager Linux Release Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      BUILD_ENV: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 16

      - name: Install NPM Dependencies
        run: npm ci

      - name: Build Linux Release Candidate
        run: npm run action server_manager/electron_app/build linux -- --buildMode=release

      - name: Upload Linux Release Candidate
        uses: actions/upload-artifact@v2
        with:
          name: manager_linux_release_${{ github.sha }}
          path: build/server_manager/electron_app/static/dist
          if-no-files-found: error
